services:
  inventory_app_fe:
    image: inventory_app_fe:latest
    container_name: inventory_app_fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env