services:
  store_frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8081/inventory/api
    ports:
      - "3000:3000"
    image: inventory_fe:latest
    container_name: inventory_frontend
    restart: unless-stopped
