services:
  store_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: inventory_fe:latest
    container_name: inventory_frontend
    restart: unless-stopped
